# Generated by Django 4.1.2 on 2022-10-28 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date_released', models.DateField(default=datetime.datetime.today)),
                ('likes', models.IntegerField()),
                ('artiste_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
                ('artistes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste', to='musicapp.artiste')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('song_id', models.CharField(max_length=50)),
                ('song_artistes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='musicapp.song')),
            ],
            options={
                'verbose_name': 'Lyric',
                'verbose_name_plural': 'Lyrics',
            },
        ),
    ]
